from os import PathLike
from typing import Any, TypeAlias

Buffer: TypeAlias = Any  # collections.abc.Buffer needs Python 3.12

__version__: str
DIGEST_CHUNK: int

def core_version() -> str: ...

# hwinfo
def hwinfo_memory() -> dict[str, Any]: ...
def hwinfo_cpu() -> dict[str, Any]: ...
def hwinfo_process_rss() -> int: ...
def hwinfo_disk(path: str | PathLike[str]) -> dict[str, Any]: ...

# pressure (γ, v0.3): raises NotImplementedError where the OS offers no signal
def pressure_current() -> dict[str, Any]: ...

# spill engine (buffers are borrowed through the buffer protocol, RS2)
def engine_digest(data: Buffer) -> bytes: ...
def engine_digest_parts(data: Buffer) -> bytes: ...
def engine_digest_combine(length: int, parts: bytes) -> bytes: ...
def engine_read_source_into(
    path: str | PathLike[str], offset: int, dst: Buffer, expected: bytes | None = None
) -> bytes: ...
def engine_write(data: Buffer, directory: str | PathLike[str]) -> tuple[str, int, bytes]: ...

# lossless in-RAM codec
class Compressed:
    @property
    def raw_bytes(self) -> int: ...
    @property
    def stored_bytes(self) -> int: ...
    def unpack_into(self, dst: Buffer) -> None: ...

def codec_pack(data: Buffer, itemsize: int, level: int = 1) -> Compressed: ...
