from os import PathLike
from typing import Any, TypeAlias

Buffer: TypeAlias = Any  # collections.abc.Buffer needs Python 3.12

__version__: str
DIGEST_CHUNK: int

def core_version() -> str: ...

# hwinfo
def hwinfo_memory() -> dict[str, Any]: ...
def hwinfo_cpu() -> dict[str, Any]: ...
def hwinfo_process_rss() -> int: ...
def hwinfo_disk(path: str | PathLike[str]) -> dict[str, Any]: ...

# pressure (γ, v0.3): raises NotImplementedError where the OS offers no signal
def pressure_current() -> dict[str, Any]: ...

# spill engine (buffers are borrowed through the buffer protocol, RS2)
def engine_digest(data: Buffer) -> bytes: ...
def engine_digest_parts(data: Buffer) -> bytes: ...
def engine_digest_combine(length: int, parts: bytes) -> bytes: ...
def engine_read_source_into(
    path: str | PathLike[str], offset: int, dst: Buffer, expected: bytes | None = None
) -> bytes: ...
def engine_write(data: Buffer, directory: str | PathLike[str]) -> tuple[str, int, bytes]: ...

# lossless in-RAM codec
class Compressed:
    @property
    def raw_bytes(self) -> int: ...
    @property
    def stored_bytes(self) -> int: ...
    def unpack_into(self, dst: Buffer) -> None: ...

def codec_pack(data: Buffer, itemsize: int, level: int = 1) -> Compressed: ...

# runtime C-R (0112): buffers under a hard budget, dropped/re-read or compressed, never written
class RtPin:
    """A pinned buffer; exposes the buffer protocol (zero-copy views)."""

    @property
    def nbytes(self) -> int: ...
    @property
    def writable(self) -> bool: ...
    @property
    def views(self) -> int: ...
    @property
    def unpinned(self) -> bool: ...
    @property
    def address(self) -> int: ...
    def release(self) -> None: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...

class RtRuntime:
    def __init__(
        self,
        budget: int,
        compress_level: int = 1,
        min_saving: float = 0.15,
        policy: str = "reuse",
        prefetch: bool = True,
        lookahead: int = 64 << 20,
        process_budget: int | None = None,
    ) -> None: ...
    def limit(self) -> int: ...
    def alloc(self, nbytes: int, elem: int) -> int: ...
    def add_file(self, path: str | PathLike[str], offset: int, nbytes: int, elem: int) -> int: ...
    def hold_back(self, nbytes: int) -> None: ...
    def pin(self, id: int, write: bool = False) -> RtPin: ...
    def free(self, id: int) -> None: ...
    def prefetch(self, id: int) -> None: ...
    # phase 2 (0115): func(out, inputs) fills `out` (a memoryview valid during the call) from
    # `inputs` (RtPin objects); re-run and digest-checked when the buffer comes back
    def derive(self, inputs: list[int], nbytes: int, elem: int, func: Any) -> int: ...
    def predict(self) -> dict[str, Any] | None: ...
    def evict(self, id: int) -> bool: ...
    def state(self, id: int) -> str: ...
    def nbytes(self, id: int) -> int: ...
    def stats(self) -> dict[str, Any]: ...

# transparent paging (0124 Linux userfaultfd, 0229 macOS signals; elsewhere the constructor
# raises NotImplementedError)
class RtPager:
    def __init__(
        self,
        budget: int,
        chunk: int = 1 << 20,
        elem: int = 4,
        compress_level: int = 1,
        min_saving: float = 0.15,
        threshold: int = 16 << 20,
        process_budget: int | None = None,
    ) -> None: ...
    def limit(self) -> int: ...
    def map(self, nbytes: int) -> int: ...
    def unmap(self, address: int) -> int: ...
    def stats(self) -> dict[str, Any]: ...
    def numpy_handler(self) -> Any: ...

def numpy_set_handler(handler: Any | None) -> Any: ...
def process_footprint() -> int | None: ...

# G4 E1 (0130): a no-copy Metal buffer over page-aligned memory (macOS; returns the id<MTLBuffer>)
def metal_wrap(address: int, length: int) -> int: ...
def metal_release(buffer: int) -> None: ...
